#!/bin/sh
# Run upstream runtime tests
# Assumes $AUTOPKGTEST_TMP is set, see /usr/share/doc/autopkgtest/README.package-tests.gz
set -e

# We just copy and run the entire test suite to resp. from the $AUTOPKGTEST_TMP
# directory because it generates output within each test's source directory.
cp -r tests "$AUTOPKGTEST_TMP"
cd "$AUTOPKGTEST_TMP"/tests
make run

# Save all test output files so that they can be accessed from ci.debian.net
cp -r keyctl "$AUTOPKGTEST_ARTIFACTS"
